version: '3.8'

services:
  yacht:
    image: selfhostedpro/yacht:latest
    container_name: yacht
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - yacht_data:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - servicenet

volumes:
  yacht_data:
    external: false

networks:
  servicenet:
    external: true